name: chesslinkdriver
description: A ChessLink ChessLink-Chessboard Driver written in pure Dart
version: 0.0.10
repository: https://github.com/mono424/chesslinkdriver

environment:
  sdk: ">=2.18.0 <3.0.0"
