name: chesslinkdriver
description: A ChessLink ChessLink-Chessboard Driver written in pure Dart
version: 0.0.3
repository: https://github.com/mono424/chesslinkdriver

environment:
  sdk: ">=2.7.0 <3.0.0"
